#!/usr/bin/env python3
"""Generate serde models from the four vendored Qubic API specifications."""
from __future__ import annotations
import argparse, json, keyword, re, subprocess, tempfile
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
SPECS = {
    "live": ROOT / "docs/qubic-http.openapi.yaml",
    "query": ROOT / "docs/query_services.openapi.yaml",
    "archive": ROOT / "docs/archive.swagger.json",
    "stats": ROOT / "docs/stats-api.swagger.json",
}

def load(path: Path):
    with path.open(encoding="utf-8-sig") as f:
        return json.load(f) if path.suffix == ".json" else yaml.safe_load(f)

def snake(name: str) -> str:
    value = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    value = re.sub(r"[^A-Za-z0-9_]", "_", value).lower()
    if not value or value[0].isdigit(): value = "field_" + value
    if keyword.iskeyword(value) or value in {"type", "ref", "self", "crate", "super", "mod", "move", "box", "use", "match", "loop", "in", "where", "async", "await", "dyn"}: value += "_"
    return value

def camel(name: str) -> str:
    first, *rest = name.split("_")
    return first + "".join(part.title() for part in rest)

def ref_name(ref: str) -> str: return ref.rsplit("/", 1)[-1]

def rust_type(schema: dict) -> str:
    if not schema: return "serde_json::Value"
    if "$ref" in schema: return ref_name(schema["$ref"])
    if "allOf" in schema and len(schema["allOf"]) == 1: return rust_type(schema["allOf"][0])
    typ = schema.get("type")
    fmt = schema.get("format")
    if typ == "array": return f"Vec<{rust_type(schema.get('items', {}))}>"
    if typ == "object":
        extra = schema.get("additionalProperties")
        if extra is not None: return f"std::collections::BTreeMap<String, {rust_type(extra if isinstance(extra, dict) else {})}>"
        return "serde_json::Value"
    if typ == "integer":
        return {"uint32":"u32", "uint64":"u64", "int32":"i32", "int64":"i64"}.get(fmt, "i64")
    if typ == "number": return "f32" if fmt == "float" else "f64"
    if typ == "boolean": return "bool"
    if typ == "string": return "String"
    return "serde_json::Value"

def schemas(doc: dict) -> dict:
    return doc.get("components", {}).get("schemas", doc.get("definitions", {}))

def render_module(name: str, doc: dict) -> str:
    out = [f"pub mod {name} {{", "    use serde::{Deserialize, Serialize};", ""]
    for model, schema in schemas(doc).items():
        props = schema.get("properties") or {}
        required = set(schema.get("required") or [])
        if not props:
            out += ["    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]", "    #[serde(transparent)]", f"    pub struct {model}(pub {rust_type(schema)});", ""]
            continue
        out += ["    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]", f"    pub struct {model} {{"]
        for wire, field_schema in props.items():
            field = snake(wire)
            ty = rust_type(field_schema)
            optional = wire not in required or field_schema.get("nullable") is True or field_schema.get("x-nullable") is True
            attrs = [f'        #[serde(rename = "{wire}"']
            if optional: attrs[0] += ', default, skip_serializing_if = "Option::is_none"'
            attrs[0] += ")]"
            out += attrs
            out.append(f"        pub {field}: {'Option<' + ty + '>' if optional else ty},")
        out += ["    }", ""]
    out.append("}")
    return "\n".join(out)

def generate() -> str:
    header = "// @generated by tools/generate_openapi.py; do not edit manually.\n#![allow(clippy::large_enum_variant, non_camel_case_types)]\n\n"
    return header + "\n\n".join(render_module(name, load(path)) for name, path in SPECS.items()) + "\n"

PREFIXES = {
    "live": "QubicLiveService_", "query": "ArchiveQueryService_",
    "archive": "ArchiveService_", "stats": "StatsService_",
}

def operation_schema(operation: dict, response=False):
    if response:
        item = operation.get("responses", {}).get("200", {})
        return item.get("content", {}).get("application/json", {}).get("schema", item.get("schema", {}))
    return operation.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema", {})

def render_api() -> str:
    out = ["// @generated by tools/generate_openapi.py; do not edit manually.",
           "use super::{ArchiveApi, ClientError, LiveApi, QueryApi, StatsApi};",
           "use crate::openapi_models::{archive, live, query, stats};",
           "use reqwest::Method;", "use serde::{Deserialize, Serialize};", ""]
    for service, path in SPECS.items():
        doc = load(path); handle = service.title() + "Api"
        operations=[]
        for route, path_item in doc["paths"].items():
            common = path_item.get("parameters", [])
            for method, operation in path_item.items():
                if method not in ("get", "post", "put", "delete", "patch"): continue
                op_name = snake(operation["operationId"].removeprefix(PREFIXES[service]))
                params = common + operation.get("parameters", [])
                query_params = [p for p in params if p.get("in") == "query"]
                qname = "".join(x.title() for x in op_name.split("_")) + "Query"
                if query_params:
                    out += ["#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]", f"pub struct {qname} {{"]
                    for p in query_params:
                        ps = p.get("schema", p)
                        ty = rust_type(ps); optional = not p.get("required", False)
                        attr=f'    #[serde(rename = "{p["name"]}"'
                        if optional: attr += ', default, skip_serializing_if = "Option::is_none"'
                        out += [attr+")]", f"    pub {snake(p['name'])}: {'Option<' + ty + '>' if optional else ty},"]
                    out += ["}", ""]
                operations.append((route, method, operation, params, query_params, qname, op_name))
        out += [f"impl {handle}<'_> {{"]
        for route, method, operation, params, query_params, qname, op_name in operations:
            args=[]
            for p in params:
                if p.get("in") == "path": args.append(f"{snake(p['name'])}: {rust_type(p.get('schema', p))}")
            body=operation_schema(operation)
            if body: args.append(f"body: &{service}::{rust_type(body)}")
            if query_params: args.append(f"query: &{qname}")
            response=operation_schema(operation, True); ret=f"{service}::{rust_type(response)}"
            segments=[]
            for part in route.strip("/").split("/"):
                if part.startswith("{"): segments.append(f"{snake(part[1:-1])}.to_string()")
                else: segments.append(json.dumps(part)+".to_string()")
            q="Some(query)" if query_params else "None::<&()>"
            b="Some(body)" if body else "None::<&()>"
            out += [f"    pub async fn {op_name}(&self{', ' if args else ''}{', '.join(args)}) -> Result<{ret}, ClientError> {{",
                    f"        self.0.request(&self.0.config.{service}_url, Method::{method.upper()}, &[{', '.join(segments)}], {q}, {b}).await", "    }"]
        out += ["}", ""]
    return "\n".join(out)

def collect_operations(service: str, doc: dict):
    operations = []
    for route, path_item in doc["paths"].items():
        common = path_item.get("parameters", [])
        for method, operation in path_item.items():
            if method not in ("get", "post", "put", "delete", "patch"):
                continue
            op_name = snake(operation["operationId"].removeprefix(PREFIXES[service]))
            params = common + operation.get("parameters", [])
            operations.append((operation, params, op_name))
    return operations

def render_wasm() -> str:
    out = [
        "// @generated by tools/generate_openapi.py; do not edit manually.",
        "use js_sys::Promise;",
        "use wasm_bindgen::prelude::*;",
        "use wasm_bindgen_futures::future_to_promise;",
        "",
    ]
    for service in SPECS:
        handle = service.title() + "ApiHandle"
        js_class = service.title() + "Api"
        out += [
            f"#[wasm_bindgen(js_name = {js_class})]",
            f"pub struct {handle} {{",
            "    client: crate::QubicClient,",
            "}",
            "",
            f"impl {handle} {{",
            "    pub(super) fn new(client: crate::QubicClient) -> Self {",
            "        Self { client }",
            "    }",
            "}",
            "",
            f"#[wasm_bindgen(js_class = {js_class})]",
            f"impl {handle} {{",
        ]
        for operation, params, op_name in collect_operations(service, load(SPECS[service])):
            args = []
            call_args = []
            conversions = []
            for p in params:
                if p.get("in") == "path":
                    pname = snake(p["name"])
                    args.append(f"{pname}: {rust_type(p.get('schema', p))}")
                    call_args.append(pname)
            body = operation_schema(operation)
            if body:
                args.append("body: JsValue")
                conversions.append("let body = super::js_to_typed(body)?;")
                call_args.append("&body")
            query_params = [p for p in params if p.get("in") == "query"]
            if query_params:
                args.append("query: JsValue")
                conversions.append("let query = super::js_to_typed(query)?;")
                call_args.append("&query")
            out += [
                f'    #[wasm_bindgen(js_name = {camel(op_name)}, unchecked_return_type = "Promise<object>")]',
                f"    pub fn {op_name}(&self{', ' if args else ''}{', '.join(args)}) -> Promise {{",
                "        let client = self.client.clone();",
                "        future_to_promise(async move {",
            ]
            out += [f"            {line}" for line in conversions]
            call = f"client.{service}().{op_name}({', '.join(call_args)})"
            out += [
                f"            let response = {call}.await",
                "                .map_err(|error| JsValue::from_str(&error.to_string()))?;",
                "            super::into_js_value(response)",
                "        })",
                "    }",
            ]
        out += ["}", ""]
    return "\n".join(out)

def main():
    parser=argparse.ArgumentParser(); parser.add_argument("--check", action="store_true"); args=parser.parse_args()
    def formatted(source: str) -> str:
        with tempfile.NamedTemporaryFile("w", suffix=".rs", encoding="utf-8", newline="\n", delete=False) as f:
            f.write(source); name=f.name
        subprocess.run(["rustfmt", "--edition", "2021", name], check=True)
        result=Path(name).read_text(encoding="utf-8"); Path(name).unlink()
        return result
    target=ROOT / "src/openapi_models.rs"; result=formatted(generate())
    api_target=ROOT / "src/client/openapi_api.rs"; api_result=formatted(render_api())
    wasm_target=ROOT / "src/wasm_openapi.rs"; wasm_result=formatted(render_wasm())
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != result or not api_target.exists() or api_target.read_text(encoding="utf-8") != api_result or not wasm_target.exists() or wasm_target.read_text(encoding="utf-8") != wasm_result: raise SystemExit("generated OpenAPI code is stale")
    else:
        target.write_text(result, encoding="utf-8", newline="\n")
        api_target.parent.mkdir(exist_ok=True)
        api_target.write_text(api_result, encoding="utf-8", newline="\n")
        wasm_target.write_text(wasm_result, encoding="utf-8", newline="\n")
if __name__ == "__main__": main()
