// @generated by tools/generate_openapi.py; do not edit manually.
#![allow(clippy::large_enum_variant, non_camel_case_types)]

pub mod live {
    use serde::{Deserialize, Serialize};

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetInfo {
        #[serde(rename = "tick", default, skip_serializing_if = "Option::is_none")]
        pub tick: Option<u32>,
        #[serde(
            rename = "universeIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub universe_index: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetIssuance {
        #[serde(rename = "data", default, skip_serializing_if = "Option::is_none")]
        pub data: Option<AssetIssuanceData>,
        #[serde(rename = "tick", default, skip_serializing_if = "Option::is_none")]
        pub tick: Option<u32>,
        #[serde(
            rename = "universeIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub universe_index: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetIssuanceData {
        #[serde(
            rename = "issuerIdentity",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub issuer_identity: Option<String>,
        #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
        pub type_: Option<u32>,
        #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        #[serde(
            rename = "numberOfDecimalPlaces",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_decimal_places: Option<i32>,
        #[serde(
            rename = "unitOfMeasurement",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub unit_of_measurement: Option<Vec<i32>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetIssuances {
        #[serde(rename = "assets", default, skip_serializing_if = "Option::is_none")]
        pub assets: Option<Vec<AssetIssuance>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetOwnership {
        #[serde(rename = "data", default, skip_serializing_if = "Option::is_none")]
        pub data: Option<AssetOwnershipData>,
        #[serde(rename = "tick", default, skip_serializing_if = "Option::is_none")]
        pub tick: Option<u32>,
        #[serde(
            rename = "universeIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub universe_index: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetOwnershipData {
        #[serde(
            rename = "ownerIdentity",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub owner_identity: Option<String>,
        #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
        pub type_: Option<u32>,
        #[serde(
            rename = "managingContractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub managing_contract_index: Option<u32>,
        #[serde(
            rename = "issuanceIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub issuance_index: Option<u32>,
        #[serde(
            rename = "numberOfUnits",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_units: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetOwnerships {
        #[serde(rename = "assets", default, skip_serializing_if = "Option::is_none")]
        pub assets: Option<Vec<AssetOwnership>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetPossession {
        #[serde(rename = "data", default, skip_serializing_if = "Option::is_none")]
        pub data: Option<AssetPossessionData>,
        #[serde(rename = "tick", default, skip_serializing_if = "Option::is_none")]
        pub tick: Option<u32>,
        #[serde(
            rename = "universeIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub universe_index: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetPossessionData {
        #[serde(
            rename = "possessorIdentity",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub possessor_identity: Option<String>,
        #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
        pub type_: Option<u32>,
        #[serde(
            rename = "managingContractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub managing_contract_index: Option<u32>,
        #[serde(
            rename = "ownershipIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub ownership_index: Option<u32>,
        #[serde(
            rename = "numberOfUnits",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_units: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetPossessions {
        #[serde(rename = "assets", default, skip_serializing_if = "Option::is_none")]
        pub assets: Option<Vec<AssetPossession>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct Balance {
        #[serde(rename = "id", default, skip_serializing_if = "Option::is_none")]
        pub id: Option<String>,
        #[serde(rename = "balance", default, skip_serializing_if = "Option::is_none")]
        pub balance: Option<String>,
        #[serde(
            rename = "validForTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub valid_for_tick: Option<u32>,
        #[serde(
            rename = "latestIncomingTransferTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub latest_incoming_transfer_tick: Option<u32>,
        #[serde(
            rename = "latestOutgoingTransferTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub latest_outgoing_transfer_tick: Option<u32>,
        #[serde(
            rename = "incomingAmount",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub incoming_amount: Option<String>,
        #[serde(
            rename = "outgoingAmount",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub outgoing_amount: Option<String>,
        #[serde(
            rename = "numberOfIncomingTransfers",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_incoming_transfers: Option<u32>,
        #[serde(
            rename = "numberOfOutgoingTransfers",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_outgoing_transfers: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct BroadcastTransactionRequest {
        #[serde(
            rename = "encodedTransaction",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub encoded_transaction: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct BroadcastTransactionResponse {
        #[serde(
            rename = "peersBroadcasted",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub peers_broadcasted: Option<i32>,
        #[serde(
            rename = "encodedTransaction",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub encoded_transaction: Option<String>,
        #[serde(
            rename = "transactionId",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transaction_id: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetActiveIposResponse {
        #[serde(rename = "ipos", default, skip_serializing_if = "Option::is_none")]
        pub ipos: Option<Vec<Ipo>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetBalanceResponse {
        #[serde(rename = "balance", default, skip_serializing_if = "Option::is_none")]
        pub balance: Option<Balance>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetBlockHeightResponse {
        #[serde(
            rename = "blockHeight",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub block_height: Option<TickInfo>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetContractIpoBidsResponse {
        #[serde(rename = "bidData", default, skip_serializing_if = "Option::is_none")]
        pub bid_data: Option<IpoBidData>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetTickInfoResponse {
        #[serde(rename = "tickInfo", default, skip_serializing_if = "Option::is_none")]
        pub tick_info: Option<TickInfo>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct Ipo {
        #[serde(
            rename = "contractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub contract_index: Option<u32>,
        #[serde(rename = "assetName", default, skip_serializing_if = "Option::is_none")]
        pub asset_name: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct IpoBid {
        #[serde(rename = "identity", default, skip_serializing_if = "Option::is_none")]
        pub identity: Option<String>,
        #[serde(rename = "amount", default, skip_serializing_if = "Option::is_none")]
        pub amount: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct IpoBidData {
        #[serde(
            rename = "contractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub contract_index: Option<u32>,
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<u32>,
        #[serde(rename = "bids", default, skip_serializing_if = "Option::is_none")]
        pub bids: Option<std::collections::BTreeMap<String, IpoBid>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct IssuedAsset {
        #[serde(rename = "data", default, skip_serializing_if = "Option::is_none")]
        pub data: Option<IssuedAssetData>,
        #[serde(rename = "info", default, skip_serializing_if = "Option::is_none")]
        pub info: Option<AssetInfo>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct IssuedAssetData {
        #[serde(
            rename = "issuerIdentity",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub issuer_identity: Option<String>,
        #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
        pub type_: Option<u32>,
        #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        #[serde(
            rename = "numberOfDecimalPlaces",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_decimal_places: Option<i32>,
        #[serde(
            rename = "unitOfMeasurement",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub unit_of_measurement: Option<Vec<i32>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct IssuedAssetsResponse {
        #[serde(
            rename = "issuedAssets",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub issued_assets: Option<Vec<IssuedAsset>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct OwnedAsset {
        #[serde(rename = "data", default, skip_serializing_if = "Option::is_none")]
        pub data: Option<OwnedAssetData>,
        #[serde(rename = "info", default, skip_serializing_if = "Option::is_none")]
        pub info: Option<AssetInfo>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct OwnedAssetData {
        #[serde(
            rename = "ownerIdentity",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub owner_identity: Option<String>,
        #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
        pub type_: Option<u32>,
        #[serde(rename = "padding", default, skip_serializing_if = "Option::is_none")]
        pub padding: Option<i32>,
        #[serde(
            rename = "managingContractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub managing_contract_index: Option<u32>,
        #[serde(
            rename = "issuanceIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub issuance_index: Option<u32>,
        #[serde(
            rename = "numberOfUnits",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_units: Option<String>,
        #[serde(
            rename = "issuedAsset",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub issued_asset: Option<IssuedAssetData>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct OwnedAssetsResponse {
        #[serde(
            rename = "ownedAssets",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub owned_assets: Option<Vec<OwnedAsset>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct PossessedAsset {
        #[serde(rename = "data", default, skip_serializing_if = "Option::is_none")]
        pub data: Option<PossessedAssetData>,
        #[serde(rename = "info", default, skip_serializing_if = "Option::is_none")]
        pub info: Option<AssetInfo>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct PossessedAssetData {
        #[serde(
            rename = "possessorIdentity",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub possessor_identity: Option<String>,
        #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
        pub type_: Option<u32>,
        #[serde(rename = "padding", default, skip_serializing_if = "Option::is_none")]
        pub padding: Option<i32>,
        #[serde(
            rename = "managingContractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub managing_contract_index: Option<u32>,
        #[serde(
            rename = "issuanceIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub issuance_index: Option<u32>,
        #[serde(
            rename = "numberOfUnits",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_units: Option<String>,
        #[serde(
            rename = "ownedAsset",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub owned_asset: Option<OwnedAssetData>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct PossessedAssetsResponse {
        #[serde(
            rename = "possessedAssets",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub possessed_assets: Option<Vec<PossessedAsset>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct QuerySmartContractRequest {
        #[serde(
            rename = "contractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub contract_index: Option<u32>,
        #[serde(rename = "inputType", default, skip_serializing_if = "Option::is_none")]
        pub input_type: Option<u32>,
        #[serde(rename = "inputSize", default, skip_serializing_if = "Option::is_none")]
        pub input_size: Option<u32>,
        #[serde(
            rename = "requestData",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub request_data: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct QuerySmartContractResponse {
        #[serde(
            rename = "responseData",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub response_data: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct TickInfo {
        #[serde(rename = "tick", default, skip_serializing_if = "Option::is_none")]
        pub tick: Option<u32>,
        #[serde(rename = "duration", default, skip_serializing_if = "Option::is_none")]
        pub duration: Option<u32>,
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<u32>,
        #[serde(
            rename = "initialTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub initial_tick: Option<u32>,
    }
}

pub mod query {
    use serde::{Deserialize, Serialize};

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetIssuanceData {
        #[serde(
            rename = "assetIssuer",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub asset_issuer: Option<String>,
        #[serde(
            rename = "numberOfShares",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_shares: Option<String>,
        #[serde(
            rename = "managingContractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub managing_contract_index: Option<String>,
        #[serde(rename = "assetName", default, skip_serializing_if = "Option::is_none")]
        pub asset_name: Option<String>,
        #[serde(
            rename = "numberOfDecimalPlaces",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_decimal_places: Option<u32>,
        #[serde(
            rename = "unitOfMeasurement",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub unit_of_measurement: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetOwnershipChangeData {
        #[serde(rename = "source", default, skip_serializing_if = "Option::is_none")]
        pub source: Option<String>,
        #[serde(
            rename = "destination",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub destination: Option<String>,
        #[serde(
            rename = "assetIssuer",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub asset_issuer: Option<String>,
        #[serde(rename = "assetName", default, skip_serializing_if = "Option::is_none")]
        pub asset_name: Option<String>,
        #[serde(
            rename = "numberOfShares",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_shares: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetOwnershipManagingContractChangeData {
        #[serde(rename = "assetName", default, skip_serializing_if = "Option::is_none")]
        pub asset_name: Option<String>,
        #[serde(
            rename = "assetIssuer",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub asset_issuer: Option<String>,
        #[serde(rename = "owner", default, skip_serializing_if = "Option::is_none")]
        pub owner: Option<String>,
        #[serde(
            rename = "numberOfShares",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_shares: Option<String>,
        #[serde(
            rename = "sourceContractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub source_contract_index: Option<String>,
        #[serde(
            rename = "destinationContractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub destination_contract_index: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetPossessionChangeData {
        #[serde(rename = "source", default, skip_serializing_if = "Option::is_none")]
        pub source: Option<String>,
        #[serde(
            rename = "destination",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub destination: Option<String>,
        #[serde(
            rename = "assetIssuer",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub asset_issuer: Option<String>,
        #[serde(rename = "assetName", default, skip_serializing_if = "Option::is_none")]
        pub asset_name: Option<String>,
        #[serde(
            rename = "numberOfShares",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_shares: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct AssetPossessionManagingContractChangeData {
        #[serde(rename = "assetName", default, skip_serializing_if = "Option::is_none")]
        pub asset_name: Option<String>,
        #[serde(
            rename = "assetIssuer",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub asset_issuer: Option<String>,
        #[serde(rename = "owner", default, skip_serializing_if = "Option::is_none")]
        pub owner: Option<String>,
        #[serde(rename = "possessor", default, skip_serializing_if = "Option::is_none")]
        pub possessor: Option<String>,
        #[serde(
            rename = "numberOfShares",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_shares: Option<String>,
        #[serde(
            rename = "sourceContractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub source_contract_index: Option<String>,
        #[serde(
            rename = "destinationContractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub destination_contract_index: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct BurningData {
        #[serde(rename = "source", default, skip_serializing_if = "Option::is_none")]
        pub source: Option<String>,
        #[serde(rename = "amount", default, skip_serializing_if = "Option::is_none")]
        pub amount: Option<String>,
        #[serde(
            rename = "contractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub contract_index: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct ComputorList {
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<u32>,
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<u32>,
        #[serde(
            rename = "identities",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub identities: Option<Vec<String>>,
        #[serde(rename = "signature", default, skip_serializing_if = "Option::is_none")]
        pub signature: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct ContractReserveDeductionData {
        #[serde(
            rename = "deductedAmount",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub deducted_amount: Option<String>,
        #[serde(
            rename = "remainingAmount",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub remaining_amount: Option<String>,
        #[serde(
            rename = "contractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub contract_index: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct CustomMessageData {
        #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
        pub value: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct Event {
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<u32>,
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<u32>,
        #[serde(rename = "timestamp", default, skip_serializing_if = "Option::is_none")]
        pub timestamp: Option<String>,
        #[serde(
            rename = "transactionHash",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transaction_hash: Option<String>,
        #[serde(rename = "logType", default, skip_serializing_if = "Option::is_none")]
        pub log_type: Option<u32>,
        #[serde(rename = "logId", default, skip_serializing_if = "Option::is_none")]
        pub log_id: Option<String>,
        #[serde(rename = "logDigest", default, skip_serializing_if = "Option::is_none")]
        pub log_digest: Option<String>,
        #[serde(
            rename = "categories",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub categories: Option<Vec<i32>>,
        #[serde(
            rename = "rawPayload",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub raw_payload: Option<String>,
        #[serde(
            rename = "quTransfer",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub qu_transfer: Option<QuTransferData>,
        #[serde(
            rename = "assetIssuance",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub asset_issuance: Option<AssetIssuanceData>,
        #[serde(
            rename = "assetOwnershipChange",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub asset_ownership_change: Option<AssetOwnershipChangeData>,
        #[serde(
            rename = "assetPossessionChange",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub asset_possession_change: Option<AssetPossessionChangeData>,
        #[serde(rename = "burning", default, skip_serializing_if = "Option::is_none")]
        pub burning: Option<BurningData>,
        #[serde(
            rename = "contractReserveDeduction",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub contract_reserve_deduction: Option<ContractReserveDeductionData>,
        #[serde(
            rename = "smartContractMessage",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub smart_contract_message: Option<SmartContractMessageData>,
        #[serde(
            rename = "customMessage",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub custom_message: Option<CustomMessageData>,
        #[serde(
            rename = "assetOwnershipManagingContractChange",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub asset_ownership_managing_contract_change:
            Option<AssetOwnershipManagingContractChangeData>,
        #[serde(
            rename = "assetPossessionManagingContractChange",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub asset_possession_managing_contract_change:
            Option<AssetPossessionManagingContractChangeData>,
        #[serde(
            rename = "oracleQueryStatusChange",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub oracle_query_status_change: Option<OracleQueryStatusChangeData>,
        #[serde(
            rename = "oracleSubscriberLogMessage",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub oracle_subscriber_log_message: Option<OracleSubscriberLogMessageData>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetComputorListsForEpochRequest {
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetComputorListsForEpochResponse {
        #[serde(
            rename = "computorsLists",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub computors_lists: Option<Vec<ComputorList>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetEventLogsRequest {
        #[serde(rename = "filters", default, skip_serializing_if = "Option::is_none")]
        pub filters: Option<std::collections::BTreeMap<String, String>>,
        #[serde(rename = "exclude", default, skip_serializing_if = "Option::is_none")]
        pub exclude: Option<std::collections::BTreeMap<String, String>>,
        #[serde(rename = "should", default, skip_serializing_if = "Option::is_none")]
        pub should: Option<Vec<ShouldFilter>>,
        #[serde(rename = "ranges", default, skip_serializing_if = "Option::is_none")]
        pub ranges: Option<std::collections::BTreeMap<String, Range>>,
        #[serde(
            rename = "pagination",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub pagination: Option<Pagination>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetEventLogsResponse {
        #[serde(rename = "hits", default, skip_serializing_if = "Option::is_none")]
        pub hits: Option<Hits>,
        #[serde(rename = "eventLogs", default, skip_serializing_if = "Option::is_none")]
        pub event_logs: Option<Vec<Event>>,
        #[serde(
            rename = "validForTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub valid_for_tick: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetLastProcessedTickResponse {
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<u32>,
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<u32>,
        #[serde(
            rename = "intervalInitialTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub interval_initial_tick: Option<u32>,
        #[serde(
            rename = "logTickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub log_tick_number: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetProcessedTickIntervalsResponse {
        #[serde(
            rename = "processedTickIntervals",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub processed_tick_intervals: Option<Vec<ProcessedTickInterval>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetTickDataRequest {
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetTickDataResponse {
        #[serde(rename = "tickData", default, skip_serializing_if = "Option::is_none")]
        pub tick_data: Option<TickData>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetTransactionByHashRequest {
        #[serde(rename = "hash", default, skip_serializing_if = "Option::is_none")]
        pub hash: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetTransactionByHashResponse {
        #[serde(
            rename = "transaction",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transaction: Option<Transaction>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetTransactionsForIdentityRequest {
        #[serde(rename = "identity", default, skip_serializing_if = "Option::is_none")]
        pub identity: Option<String>,
        #[serde(rename = "filters", default, skip_serializing_if = "Option::is_none")]
        pub filters: Option<std::collections::BTreeMap<String, String>>,
        #[serde(rename = "exclude", default, skip_serializing_if = "Option::is_none")]
        pub exclude: Option<std::collections::BTreeMap<String, String>>,
        #[serde(rename = "ranges", default, skip_serializing_if = "Option::is_none")]
        pub ranges: Option<std::collections::BTreeMap<String, Range>>,
        #[serde(
            rename = "pagination",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub pagination: Option<Pagination>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetTransactionsForIdentityResponse {
        #[serde(
            rename = "validForTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub valid_for_tick: Option<u32>,
        #[serde(rename = "hits", default, skip_serializing_if = "Option::is_none")]
        pub hits: Option<Hits>,
        #[serde(
            rename = "transactions",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transactions: Option<Vec<Transaction>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetTransactionsForTickRequest {
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<u32>,
        #[serde(rename = "filters", default, skip_serializing_if = "Option::is_none")]
        pub filters: Option<std::collections::BTreeMap<String, String>>,
        #[serde(rename = "ranges", default, skip_serializing_if = "Option::is_none")]
        pub ranges: Option<std::collections::BTreeMap<String, Range>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct GetTransactionsForTickResponse {
        #[serde(
            rename = "transactions",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transactions: Option<Vec<Transaction>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct HealthResponse {
        #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
        pub status: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct Hits {
        #[serde(rename = "total", default, skip_serializing_if = "Option::is_none")]
        pub total: Option<u32>,
        #[serde(rename = "from", default, skip_serializing_if = "Option::is_none")]
        pub from_: Option<u32>,
        #[serde(rename = "size", default, skip_serializing_if = "Option::is_none")]
        pub size: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct OracleQueryStatusChangeData {
        #[serde(
            rename = "queryingEntity",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub querying_entity: Option<String>,
        #[serde(rename = "queryId", default, skip_serializing_if = "Option::is_none")]
        pub query_id: Option<String>,
        #[serde(
            rename = "interfaceIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub interface_index: Option<String>,
        #[serde(rename = "queryType", default, skip_serializing_if = "Option::is_none")]
        pub query_type: Option<String>,
        #[serde(
            rename = "queryStatus",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub query_status: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct OracleSubscriberLogMessageData {
        #[serde(
            rename = "subscriptionId",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub subscription_id: Option<String>,
        #[serde(
            rename = "interfaceIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub interface_index: Option<String>,
        #[serde(
            rename = "contractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub contract_index: Option<String>,
        #[serde(
            rename = "periodMillis",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub period_millis: Option<String>,
        #[serde(
            rename = "firstQueryTimestamp",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub first_query_timestamp: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct Pagination {
        #[serde(rename = "offset", default, skip_serializing_if = "Option::is_none")]
        pub offset: Option<u32>,
        #[serde(rename = "size", default, skip_serializing_if = "Option::is_none")]
        pub size: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct ProcessedTickInterval {
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<u32>,
        #[serde(rename = "firstTick", default, skip_serializing_if = "Option::is_none")]
        pub first_tick: Option<u32>,
        #[serde(rename = "lastTick", default, skip_serializing_if = "Option::is_none")]
        pub last_tick: Option<u32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct QuTransferData {
        #[serde(rename = "source", default, skip_serializing_if = "Option::is_none")]
        pub source: Option<String>,
        #[serde(
            rename = "destination",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub destination: Option<String>,
        #[serde(rename = "amount", default, skip_serializing_if = "Option::is_none")]
        pub amount: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct Range {
        #[serde(rename = "gt", default, skip_serializing_if = "Option::is_none")]
        pub gt: Option<String>,
        #[serde(rename = "gte", default, skip_serializing_if = "Option::is_none")]
        pub gte: Option<String>,
        #[serde(rename = "lt", default, skip_serializing_if = "Option::is_none")]
        pub lt: Option<String>,
        #[serde(rename = "lte", default, skip_serializing_if = "Option::is_none")]
        pub lte: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct ShouldFilter {
        #[serde(rename = "terms", default, skip_serializing_if = "Option::is_none")]
        pub terms: Option<std::collections::BTreeMap<String, String>>,
        #[serde(rename = "ranges", default, skip_serializing_if = "Option::is_none")]
        pub ranges: Option<std::collections::BTreeMap<String, Range>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct SmartContractMessageData {
        #[serde(
            rename = "contractIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub contract_index: Option<String>,
        #[serde(
            rename = "contractMessageType",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub contract_message_type: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct TickData {
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<u32>,
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<u32>,
        #[serde(
            rename = "computorIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub computor_index: Option<u32>,
        #[serde(rename = "timestamp", default, skip_serializing_if = "Option::is_none")]
        pub timestamp: Option<String>,
        #[serde(rename = "varStruct", default, skip_serializing_if = "Option::is_none")]
        pub var_struct: Option<String>,
        #[serde(rename = "timeLock", default, skip_serializing_if = "Option::is_none")]
        pub time_lock: Option<String>,
        #[serde(
            rename = "transactionHashes",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transaction_hashes: Option<Vec<String>>,
        #[serde(
            rename = "contractFees",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub contract_fees: Option<Vec<String>>,
        #[serde(rename = "signature", default, skip_serializing_if = "Option::is_none")]
        pub signature: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct Transaction {
        #[serde(rename = "hash", default, skip_serializing_if = "Option::is_none")]
        pub hash: Option<String>,
        #[serde(rename = "amount", default, skip_serializing_if = "Option::is_none")]
        pub amount: Option<String>,
        #[serde(rename = "source", default, skip_serializing_if = "Option::is_none")]
        pub source: Option<String>,
        #[serde(
            rename = "destination",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub destination: Option<String>,
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<u32>,
        #[serde(rename = "timestamp", default, skip_serializing_if = "Option::is_none")]
        pub timestamp: Option<String>,
        #[serde(rename = "inputType", default, skip_serializing_if = "Option::is_none")]
        pub input_type: Option<u32>,
        #[serde(rename = "inputSize", default, skip_serializing_if = "Option::is_none")]
        pub input_size: Option<u32>,
        #[serde(rename = "inputData", default, skip_serializing_if = "Option::is_none")]
        pub input_data: Option<String>,
        #[serde(rename = "signature", default, skip_serializing_if = "Option::is_none")]
        pub signature: Option<String>,
        #[serde(rename = "moneyFlew", default, skip_serializing_if = "Option::is_none")]
        pub money_flew: Option<bool>,
    }
}

pub mod archive {
    use serde::{Deserialize, Serialize};

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbComputors {
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<i64>,
        #[serde(
            rename = "identities",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub identities: Option<Vec<String>>,
        #[serde(
            rename = "signatureHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub signature_hex: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetChainHashResponse {
        #[serde(rename = "hexDigest", default, skip_serializing_if = "Option::is_none")]
        pub hex_digest: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetComputorsResponse {
        #[serde(rename = "computors", default, skip_serializing_if = "Option::is_none")]
        pub computors: Option<pbComputors>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetEmptyTickListResponseV2 {
        #[serde(
            rename = "pagination",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub pagination: Option<pbPagination>,
        #[serde(
            rename = "emptyTicks",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub empty_ticks: Option<Vec<i64>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetEpochTickListResponseV2 {
        #[serde(
            rename = "pagination",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub pagination: Option<pbPagination>,
        #[serde(rename = "ticks", default, skip_serializing_if = "Option::is_none")]
        pub ticks: Option<Vec<pbTickStatus>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetHealthCheckResponse {
        #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
        pub status: Option<bool>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetIdentityTransfersInTickRangeResponseV2 {
        #[serde(
            rename = "pagination",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub pagination: Option<pbPagination>,
        #[serde(
            rename = "transactions",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transactions: Option<Vec<pbPerTickIdentityTransfers>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetLatestTickResponse {
        #[serde(
            rename = "latestTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub latest_tick: Option<i64>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetQuorumTickDataResponse {
        #[serde(
            rename = "quorumTickData",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub quorum_tick_data: Option<pbQuorumTickData>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetSendManyTransactionResponseV2 {
        #[serde(
            rename = "transaction",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transaction: Option<pbSendManyTransaction>,
        #[serde(rename = "timestamp", default, skip_serializing_if = "Option::is_none")]
        pub timestamp: Option<String>,
        #[serde(rename = "moneyFlew", default, skip_serializing_if = "Option::is_none")]
        pub money_flew: Option<bool>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetStatusResponse {
        #[serde(
            rename = "lastProcessedTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub last_processed_tick: Option<pbProcessedTick>,
        #[serde(
            rename = "lastProcessedTicksPerEpoch",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub last_processed_ticks_per_epoch: Option<std::collections::BTreeMap<String, i64>>,
        #[serde(
            rename = "skippedTicks",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub skipped_ticks: Option<Vec<pbSkippedTicksInterval>>,
        #[serde(
            rename = "processedTickIntervalsPerEpoch",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub processed_tick_intervals_per_epoch: Option<Vec<pbProcessedTickIntervalsPerEpoch>>,
        #[serde(
            rename = "emptyTicksPerEpoch",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub empty_ticks_per_epoch: Option<std::collections::BTreeMap<String, i64>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetTickApprovedTransactionsResponse {
        #[serde(
            rename = "approvedTransactions",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub approved_transactions: Option<Vec<pbTransaction>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetTickDataResponse {
        #[serde(rename = "tickData", default, skip_serializing_if = "Option::is_none")]
        pub tick_data: Option<pbTickData>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetTickTransactionsResponse {
        #[serde(
            rename = "transactions",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transactions: Option<Vec<pbTransaction>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetTickTransactionsResponseV2 {
        #[serde(
            rename = "transactions",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transactions: Option<Vec<pbTransactionData>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetTransactionResponse {
        #[serde(
            rename = "transaction",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transaction: Option<pbTransaction>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetTransactionResponseV2 {
        #[serde(
            rename = "transaction",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transaction: Option<pbTransaction>,
        #[serde(rename = "timestamp", default, skip_serializing_if = "Option::is_none")]
        pub timestamp: Option<String>,
        #[serde(rename = "moneyFlew", default, skip_serializing_if = "Option::is_none")]
        pub money_flew: Option<bool>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetTransactionStatusResponse {
        #[serde(
            rename = "transactionStatus",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transaction_status: Option<pbTransactionStatus>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetTransferTransactionsPerTickResponse {
        #[serde(
            rename = "transferTransactionsPerTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transfer_transactions_per_tick: Option<Vec<pbTransferTransactionsPerTick>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbPagination {
        #[serde(
            rename = "totalRecords",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub total_records: Option<i32>,
        #[serde(
            rename = "currentPage",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub current_page: Option<i32>,
        #[serde(
            rename = "totalPages",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub total_pages: Option<i32>,
        #[serde(rename = "pageSize", default, skip_serializing_if = "Option::is_none")]
        pub page_size: Option<i32>,
        #[serde(rename = "nextPage", default, skip_serializing_if = "Option::is_none")]
        pub next_page: Option<i32>,
        #[serde(
            rename = "previousPage",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub previous_page: Option<i32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbPerTickIdentityTransfers {
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<i64>,
        #[serde(rename = "identity", default, skip_serializing_if = "Option::is_none")]
        pub identity: Option<String>,
        #[serde(
            rename = "transactions",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transactions: Option<Vec<pbTransactionData>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbProcessedTick {
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<i64>,
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<i64>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbProcessedTickInterval {
        #[serde(
            rename = "initialProcessedTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub initial_processed_tick: Option<i64>,
        #[serde(
            rename = "lastProcessedTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub last_processed_tick: Option<i64>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbProcessedTickIntervalsPerEpoch {
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<i64>,
        #[serde(rename = "intervals", default, skip_serializing_if = "Option::is_none")]
        pub intervals: Option<Vec<pbProcessedTickInterval>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbQuorumDiff {
        #[serde(
            rename = "saltedResourceTestingDigestHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub salted_resource_testing_digest_hex: Option<String>,
        #[serde(
            rename = "saltedSpectrumDigestHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub salted_spectrum_digest_hex: Option<String>,
        #[serde(
            rename = "saltedUniverseDigestHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub salted_universe_digest_hex: Option<String>,
        #[serde(
            rename = "saltedComputerDigestHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub salted_computer_digest_hex: Option<String>,
        #[serde(
            rename = "expectedNextTickTxDigestHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub expected_next_tick_tx_digest_hex: Option<String>,
        #[serde(
            rename = "signatureHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub signature_hex: Option<String>,
        #[serde(
            rename = "saltedTransactionBodyHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub salted_transaction_body_hex: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbQuorumTickData {
        #[serde(
            rename = "quorumTickStructure",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub quorum_tick_structure: Option<pbQuorumTickStructure>,
        #[serde(
            rename = "quorumDiffPerComputor",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub quorum_diff_per_computor: Option<std::collections::BTreeMap<String, pbQuorumDiff>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbQuorumTickStructure {
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<i64>,
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<i64>,
        #[serde(rename = "timestamp", default, skip_serializing_if = "Option::is_none")]
        pub timestamp: Option<String>,
        #[serde(
            rename = "prevResourceTestingDigestHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub prev_resource_testing_digest_hex: Option<String>,
        #[serde(
            rename = "prevSpectrumDigestHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub prev_spectrum_digest_hex: Option<String>,
        #[serde(
            rename = "prevUniverseDigestHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub prev_universe_digest_hex: Option<String>,
        #[serde(
            rename = "prevComputerDigestHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub prev_computer_digest_hex: Option<String>,
        #[serde(
            rename = "txDigestHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tx_digest_hex: Option<String>,
        #[serde(
            rename = "prevTransactionBodyHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub prev_transaction_body_hex: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbSendManyTransaction {
        #[serde(rename = "sourceId", default, skip_serializing_if = "Option::is_none")]
        pub source_id: Option<String>,
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<i64>,
        #[serde(rename = "transfers", default, skip_serializing_if = "Option::is_none")]
        pub transfers: Option<Vec<pbSendManyTransfer>>,
        #[serde(
            rename = "totalAmount",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub total_amount: Option<String>,
        #[serde(
            rename = "signatureHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub signature_hex: Option<String>,
        #[serde(rename = "txId", default, skip_serializing_if = "Option::is_none")]
        pub tx_id: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbSendManyTransfer {
        #[serde(rename = "destId", default, skip_serializing_if = "Option::is_none")]
        pub dest_id: Option<String>,
        #[serde(rename = "amount", default, skip_serializing_if = "Option::is_none")]
        pub amount: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbSkippedTicksInterval {
        #[serde(rename = "startTick", default, skip_serializing_if = "Option::is_none")]
        pub start_tick: Option<i64>,
        #[serde(rename = "endTick", default, skip_serializing_if = "Option::is_none")]
        pub end_tick: Option<i64>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbTickData {
        #[serde(
            rename = "computorIndex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub computor_index: Option<i64>,
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<i64>,
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<i64>,
        #[serde(rename = "timestamp", default, skip_serializing_if = "Option::is_none")]
        pub timestamp: Option<String>,
        #[serde(rename = "varStruct", default, skip_serializing_if = "Option::is_none")]
        pub var_struct: Option<String>,
        #[serde(rename = "timeLock", default, skip_serializing_if = "Option::is_none")]
        pub time_lock: Option<String>,
        #[serde(
            rename = "transactionIds",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transaction_ids: Option<Vec<String>>,
        #[serde(
            rename = "contractFees",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub contract_fees: Option<Vec<String>>,
        #[serde(
            rename = "signatureHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub signature_hex: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbTickStatus {
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<i64>,
        #[serde(rename = "isEmpty", default, skip_serializing_if = "Option::is_none")]
        pub is_empty: Option<bool>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbTransaction {
        #[serde(rename = "sourceId", default, skip_serializing_if = "Option::is_none")]
        pub source_id: Option<String>,
        #[serde(rename = "destId", default, skip_serializing_if = "Option::is_none")]
        pub dest_id: Option<String>,
        #[serde(rename = "amount", default, skip_serializing_if = "Option::is_none")]
        pub amount: Option<String>,
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<i64>,
        #[serde(rename = "inputType", default, skip_serializing_if = "Option::is_none")]
        pub input_type: Option<i64>,
        #[serde(rename = "inputSize", default, skip_serializing_if = "Option::is_none")]
        pub input_size: Option<i64>,
        #[serde(rename = "inputHex", default, skip_serializing_if = "Option::is_none")]
        pub input_hex: Option<String>,
        #[serde(
            rename = "signatureHex",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub signature_hex: Option<String>,
        #[serde(rename = "txId", default, skip_serializing_if = "Option::is_none")]
        pub tx_id: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbTransactionData {
        #[serde(
            rename = "transaction",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transaction: Option<pbTransaction>,
        #[serde(rename = "timestamp", default, skip_serializing_if = "Option::is_none")]
        pub timestamp: Option<String>,
        #[serde(rename = "moneyFlew", default, skip_serializing_if = "Option::is_none")]
        pub money_flew: Option<bool>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbTransactionStatus {
        #[serde(rename = "txId", default, skip_serializing_if = "Option::is_none")]
        pub tx_id: Option<String>,
        #[serde(rename = "moneyFlew", default, skip_serializing_if = "Option::is_none")]
        pub money_flew: Option<bool>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbTransferTransactionsPerTick {
        #[serde(
            rename = "tickNumber",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub tick_number: Option<i64>,
        #[serde(rename = "identity", default, skip_serializing_if = "Option::is_none")]
        pub identity: Option<String>,
        #[serde(
            rename = "transactions",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub transactions: Option<Vec<pbTransaction>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct protobufAny {
        #[serde(rename = "@type", default, skip_serializing_if = "Option::is_none")]
        pub _type: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct rpcStatus {
        #[serde(rename = "code", default, skip_serializing_if = "Option::is_none")]
        pub code: Option<i32>,
        #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
        pub message: Option<String>,
        #[serde(rename = "details", default, skip_serializing_if = "Option::is_none")]
        pub details: Option<Vec<protobufAny>>,
    }
}

pub mod stats {
    use serde::{Deserialize, Serialize};

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbAssetOwnership {
        #[serde(rename = "identity", default, skip_serializing_if = "Option::is_none")]
        pub identity: Option<String>,
        #[serde(
            rename = "numberOfShares",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub number_of_shares: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetAssetOwnershipResponse {
        #[serde(
            rename = "pagination",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub pagination: Option<pbPagination>,
        #[serde(rename = "tick", default, skip_serializing_if = "Option::is_none")]
        pub tick: Option<i64>,
        #[serde(rename = "owners", default, skip_serializing_if = "Option::is_none")]
        pub owners: Option<Vec<pbAssetOwnership>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetLatestDataResponse {
        #[serde(rename = "data", default, skip_serializing_if = "Option::is_none")]
        pub data: Option<pbQubicData>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbGetRichListSliceResponse {
        #[serde(
            rename = "pagination",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub pagination: Option<pbPagination>,
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<i64>,
        #[serde(rename = "richList", default, skip_serializing_if = "Option::is_none")]
        pub rich_list: Option<pbRichList>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbPagination {
        #[serde(
            rename = "totalRecords",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub total_records: Option<i32>,
        #[serde(
            rename = "currentPage",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub current_page: Option<i32>,
        #[serde(
            rename = "totalPages",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub total_pages: Option<i32>,
        #[serde(rename = "pageSize", default, skip_serializing_if = "Option::is_none")]
        pub page_size: Option<i32>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbQubicData {
        #[serde(rename = "timestamp", default, skip_serializing_if = "Option::is_none")]
        pub timestamp: Option<String>,
        #[serde(
            rename = "circulatingSupply",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub circulating_supply: Option<String>,
        #[serde(
            rename = "activeAddresses",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub active_addresses: Option<i32>,
        #[serde(rename = "price", default, skip_serializing_if = "Option::is_none")]
        pub price: Option<f32>,
        #[serde(rename = "marketCap", default, skip_serializing_if = "Option::is_none")]
        pub market_cap: Option<String>,
        #[serde(rename = "epoch", default, skip_serializing_if = "Option::is_none")]
        pub epoch: Option<i64>,
        #[serde(
            rename = "currentTick",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub current_tick: Option<i64>,
        #[serde(
            rename = "ticksInCurrentEpoch",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub ticks_in_current_epoch: Option<i64>,
        #[serde(
            rename = "emptyTicksInCurrentEpoch",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub empty_ticks_in_current_epoch: Option<i64>,
        #[serde(
            rename = "epochTickQuality",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        pub epoch_tick_quality: Option<f32>,
        #[serde(rename = "burnedQus", default, skip_serializing_if = "Option::is_none")]
        pub burned_qus: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbRichList {
        #[serde(rename = "entities", default, skip_serializing_if = "Option::is_none")]
        pub entities: Option<Vec<pbRichListEntity>>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct pbRichListEntity {
        #[serde(rename = "identity", default, skip_serializing_if = "Option::is_none")]
        pub identity: Option<String>,
        #[serde(rename = "balance", default, skip_serializing_if = "Option::is_none")]
        pub balance: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct protobufAny {
        #[serde(rename = "@type", default, skip_serializing_if = "Option::is_none")]
        pub _type: Option<String>,
    }

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub struct rpcStatus {
        #[serde(rename = "code", default, skip_serializing_if = "Option::is_none")]
        pub code: Option<i32>,
        #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
        pub message: Option<String>,
        #[serde(rename = "details", default, skip_serializing_if = "Option::is_none")]
        pub details: Option<Vec<protobufAny>>,
    }
}
