// @generated by tools/generate_openapi.py; do not edit manually.
use js_sys::Promise;
use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::future_to_promise;

#[wasm_bindgen(js_name = LiveApi)]
pub struct LiveApiHandle {
    client: crate::QubicClient,
}

impl LiveApiHandle {
    pub(super) fn new(client: crate::QubicClient) -> Self {
        Self { client }
    }
}

#[wasm_bindgen(js_class = LiveApi)]
impl LiveApiHandle {
    #[wasm_bindgen(js_name = getIssuedAssetsByFilter, unchecked_return_type = "Promise<object>")]
    pub fn get_issued_assets_by_filter(&self, query: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let query = super::js_to_typed(query)?;
            let response = client
                .live()
                .get_issued_assets_by_filter(&query)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getIssuedAssetByUniverseIndex, unchecked_return_type = "Promise<object>")]
    pub fn get_issued_asset_by_universe_index(&self, index: u32) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .live()
                .get_issued_asset_by_universe_index(index)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getOwnedAssetsByFilter, unchecked_return_type = "Promise<object>")]
    pub fn get_owned_assets_by_filter(&self, query: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let query = super::js_to_typed(query)?;
            let response = client
                .live()
                .get_owned_assets_by_filter(&query)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getOwnedAssetByUniverseIndex, unchecked_return_type = "Promise<object>")]
    pub fn get_owned_asset_by_universe_index(&self, index: u32) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .live()
                .get_owned_asset_by_universe_index(index)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getPossessedAssetsByFilter, unchecked_return_type = "Promise<object>")]
    pub fn get_possessed_assets_by_filter(&self, query: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let query = super::js_to_typed(query)?;
            let response = client
                .live()
                .get_possessed_assets_by_filter(&query)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getPossessedAssetByUniverseIndex, unchecked_return_type = "Promise<object>")]
    pub fn get_possessed_asset_by_universe_index(&self, index: u32) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .live()
                .get_possessed_asset_by_universe_index(index)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getIssuedAssets, unchecked_return_type = "Promise<object>")]
    pub fn get_issued_assets(&self, identity: String) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .live()
                .get_issued_assets(identity)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getOwnedAssets, unchecked_return_type = "Promise<object>")]
    pub fn get_owned_assets(&self, identity: String) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .live()
                .get_owned_assets(identity)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getPossessedAssets, unchecked_return_type = "Promise<object>")]
    pub fn get_possessed_assets(&self, identity: String) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .live()
                .get_possessed_assets(identity)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getBalance, unchecked_return_type = "Promise<object>")]
    pub fn get_balance(&self, id: String) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .live()
                .get_balance(id)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getBlockHeight, unchecked_return_type = "Promise<object>")]
    pub fn get_block_height(&self) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .live()
                .get_block_height()
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = broadcastTransaction, unchecked_return_type = "Promise<object>")]
    pub fn broadcast_transaction(&self, body: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let body = super::js_to_typed(body)?;
            let response = client
                .live()
                .broadcast_transaction(&body)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getActiveIpos, unchecked_return_type = "Promise<object>")]
    pub fn get_active_ipos(&self) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .live()
                .get_active_ipos()
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getContractIpoBids, unchecked_return_type = "Promise<object>")]
    pub fn get_contract_ipo_bids(&self, contract_index: u32) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .live()
                .get_contract_ipo_bids(contract_index)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = querySmartContract, unchecked_return_type = "Promise<object>")]
    pub fn query_smart_contract(&self, body: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let body = super::js_to_typed(body)?;
            let response = client
                .live()
                .query_smart_contract(&body)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTickInfo, unchecked_return_type = "Promise<object>")]
    pub fn get_tick_info(&self) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .live()
                .get_tick_info()
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
}

#[wasm_bindgen(js_name = QueryApi)]
pub struct QueryApiHandle {
    client: crate::QubicClient,
}

impl QueryApiHandle {
    pub(super) fn new(client: crate::QubicClient) -> Self {
        Self { client }
    }
}

#[wasm_bindgen(js_class = QueryApi)]
impl QueryApiHandle {
    #[wasm_bindgen(js_name = getComputorsListsForEpoch, unchecked_return_type = "Promise<object>")]
    pub fn get_computors_lists_for_epoch(&self, body: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let body = super::js_to_typed(body)?;
            let response = client
                .query()
                .get_computors_lists_for_epoch(&body)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getEventLogs, unchecked_return_type = "Promise<object>")]
    pub fn get_event_logs(&self, body: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let body = super::js_to_typed(body)?;
            let response = client
                .query()
                .get_event_logs(&body)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getLastProcessedTick, unchecked_return_type = "Promise<object>")]
    pub fn get_last_processed_tick(&self) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .query()
                .get_last_processed_tick()
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getProcessedTickIntervals, unchecked_return_type = "Promise<object>")]
    pub fn get_processed_tick_intervals(&self) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .query()
                .get_processed_tick_intervals()
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTickData, unchecked_return_type = "Promise<object>")]
    pub fn get_tick_data(&self, body: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let body = super::js_to_typed(body)?;
            let response = client
                .query()
                .get_tick_data(&body)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTransactionByHash, unchecked_return_type = "Promise<object>")]
    pub fn get_transaction_by_hash(&self, body: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let body = super::js_to_typed(body)?;
            let response = client
                .query()
                .get_transaction_by_hash(&body)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTransactionsForIdentity, unchecked_return_type = "Promise<object>")]
    pub fn get_transactions_for_identity(&self, body: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let body = super::js_to_typed(body)?;
            let response = client
                .query()
                .get_transactions_for_identity(&body)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTransactionsForTick, unchecked_return_type = "Promise<object>")]
    pub fn get_transactions_for_tick(&self, body: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let body = super::js_to_typed(body)?;
            let response = client
                .query()
                .get_transactions_for_tick(&body)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
}

#[wasm_bindgen(js_name = ArchiveApi)]
pub struct ArchiveApiHandle {
    client: crate::QubicClient,
}

impl ArchiveApiHandle {
    pub(super) fn new(client: crate::QubicClient) -> Self {
        Self { client }
    }
}

#[wasm_bindgen(js_class = ArchiveApi)]
impl ArchiveApiHandle {
    #[wasm_bindgen(js_name = getComputors, unchecked_return_type = "Promise<object>")]
    pub fn get_computors(&self, epoch: i64) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_computors(epoch)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getHealthCheck, unchecked_return_type = "Promise<object>")]
    pub fn get_health_check(&self) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_health_check()
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTransferTransactionsPerTick, unchecked_return_type = "Promise<object>")]
    pub fn get_transfer_transactions_per_tick(&self, identity: String, query: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let query = super::js_to_typed(query)?;
            let response = client
                .archive()
                .get_transfer_transactions_per_tick(identity, &query)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getLatestTick, unchecked_return_type = "Promise<object>")]
    pub fn get_latest_tick(&self) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_latest_tick()
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getStatus, unchecked_return_type = "Promise<object>")]
    pub fn get_status(&self) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_status()
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTickApprovedTransactions, unchecked_return_type = "Promise<object>")]
    pub fn get_tick_approved_transactions(&self, tick_number: i64) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_tick_approved_transactions(tick_number)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getChainHash, unchecked_return_type = "Promise<object>")]
    pub fn get_chain_hash(&self, tick_number: i64) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_chain_hash(tick_number)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getQuorumTickData, unchecked_return_type = "Promise<object>")]
    pub fn get_quorum_tick_data(&self, tick_number: i64) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_quorum_tick_data(tick_number)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getStoreHash, unchecked_return_type = "Promise<object>")]
    pub fn get_store_hash(&self, tick_number: i64) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_store_hash(tick_number)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTickData, unchecked_return_type = "Promise<object>")]
    pub fn get_tick_data(&self, tick_number: i64) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_tick_data(tick_number)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTickTransactions, unchecked_return_type = "Promise<object>")]
    pub fn get_tick_transactions(&self, tick_number: i64) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_tick_transactions(tick_number)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTickTransferTransactions, unchecked_return_type = "Promise<object>")]
    pub fn get_tick_transfer_transactions(&self, tick_number: i64) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_tick_transfer_transactions(tick_number)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTransaction, unchecked_return_type = "Promise<object>")]
    pub fn get_transaction(&self, tx_id: String) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_transaction(tx_id)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTransactionStatus, unchecked_return_type = "Promise<object>")]
    pub fn get_transaction_status(&self, tx_id: String) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_transaction_status(tx_id)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getEmptyTickListV2, unchecked_return_type = "Promise<object>")]
    pub fn get_empty_tick_list_v2(&self, epoch: i64, query: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let query = super::js_to_typed(query)?;
            let response = client
                .archive()
                .get_empty_tick_list_v2(epoch, &query)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getEpochTickListV2, unchecked_return_type = "Promise<object>")]
    pub fn get_epoch_tick_list_v2(&self, epoch: i64, query: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let query = super::js_to_typed(query)?;
            let response = client
                .archive()
                .get_epoch_tick_list_v2(epoch, &query)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getIdentityTransfersInTickRangeV2, unchecked_return_type = "Promise<object>")]
    pub fn get_identity_transfers_in_tick_range_v2(
        &self,
        identity: String,
        query: JsValue,
    ) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let query = super::js_to_typed(query)?;
            let response = client
                .archive()
                .get_identity_transfers_in_tick_range_v2(identity, &query)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTickChainHashV2, unchecked_return_type = "Promise<object>")]
    pub fn get_tick_chain_hash_v2(&self, tick_number: i64) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_tick_chain_hash_v2(tick_number)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTickQuorumDataV2, unchecked_return_type = "Promise<object>")]
    pub fn get_tick_quorum_data_v2(&self, tick_number: i64) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_tick_quorum_data_v2(tick_number)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTickStoreHashV2, unchecked_return_type = "Promise<object>")]
    pub fn get_tick_store_hash_v2(&self, tick_number: i64) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_tick_store_hash_v2(tick_number)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTickTransactionsV2, unchecked_return_type = "Promise<object>")]
    pub fn get_tick_transactions_v2(&self, tick_number: i64, query: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let query = super::js_to_typed(query)?;
            let response = client
                .archive()
                .get_tick_transactions_v2(tick_number, &query)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getTransactionV2, unchecked_return_type = "Promise<object>")]
    pub fn get_transaction_v2(&self, tx_id: String) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_transaction_v2(tx_id)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getSendManyTransactionV2, unchecked_return_type = "Promise<object>")]
    pub fn get_send_many_transaction_v2(&self, tx_id: String) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .archive()
                .get_send_many_transaction_v2(tx_id)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
}

#[wasm_bindgen(js_name = StatsApi)]
pub struct StatsApiHandle {
    client: crate::QubicClient,
}

impl StatsApiHandle {
    pub(super) fn new(client: crate::QubicClient) -> Self {
        Self { client }
    }
}

#[wasm_bindgen(js_class = StatsApi)]
impl StatsApiHandle {
    #[wasm_bindgen(js_name = getAssetOwners, unchecked_return_type = "Promise<object>")]
    pub fn get_asset_owners(
        &self,
        issuer_identity: String,
        asset_name: String,
        query: JsValue,
    ) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let query = super::js_to_typed(query)?;
            let response = client
                .stats()
                .get_asset_owners(issuer_identity, asset_name, &query)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getLatestData, unchecked_return_type = "Promise<object>")]
    pub fn get_latest_data(&self) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let response = client
                .stats()
                .get_latest_data()
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
    #[wasm_bindgen(js_name = getRichListSlice, unchecked_return_type = "Promise<object>")]
    pub fn get_rich_list_slice(&self, query: JsValue) -> Promise {
        let client = self.client.clone();
        future_to_promise(async move {
            let query = super::js_to_typed(query)?;
            let response = client
                .stats()
                .get_rich_list_slice(&query)
                .await
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            super::into_js_value(response)
        })
    }
}
