// @generated by tools/generate_openapi.py; do not edit manually.
use super::{ArchiveApi, ClientError, LiveApi, QueryApi, StatsApi};
use crate::openapi_models::{archive, live, query, stats};
use reqwest::Method;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GetIssuedAssetsByFilterQuery {
    #[serde(
        rename = "issuerIdentity",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub issuer_identity: Option<String>,
    #[serde(rename = "assetName", default, skip_serializing_if = "Option::is_none")]
    pub asset_name: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GetOwnedAssetsByFilterQuery {
    #[serde(
        rename = "issuerIdentity",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub issuer_identity: Option<String>,
    #[serde(rename = "assetName", default, skip_serializing_if = "Option::is_none")]
    pub asset_name: Option<String>,
    #[serde(
        rename = "ownerIdentity",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub owner_identity: Option<String>,
    #[serde(
        rename = "ownershipManagingContract",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ownership_managing_contract: Option<u32>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GetPossessedAssetsByFilterQuery {
    #[serde(
        rename = "issuerIdentity",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub issuer_identity: Option<String>,
    #[serde(rename = "assetName", default, skip_serializing_if = "Option::is_none")]
    pub asset_name: Option<String>,
    #[serde(
        rename = "ownerIdentity",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub owner_identity: Option<String>,
    #[serde(
        rename = "possessorIdentity",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub possessor_identity: Option<String>,
    #[serde(
        rename = "ownershipManagingContract",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ownership_managing_contract: Option<u32>,
    #[serde(
        rename = "possessionManagingContract",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub possession_managing_contract: Option<u32>,
}

impl LiveApi<'_> {
    pub async fn get_issued_assets_by_filter(
        &self,
        query: &GetIssuedAssetsByFilterQuery,
    ) -> Result<live::AssetIssuances, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &["assets".to_string(), "issuances".to_string()],
                Some(query),
                None::<&()>,
            )
            .await
    }
    pub async fn get_issued_asset_by_universe_index(
        &self,
        index: u32,
    ) -> Result<live::AssetIssuance, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &[
                    "assets".to_string(),
                    "issuances".to_string(),
                    index.to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_owned_assets_by_filter(
        &self,
        query: &GetOwnedAssetsByFilterQuery,
    ) -> Result<live::AssetOwnerships, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &["assets".to_string(), "ownerships".to_string()],
                Some(query),
                None::<&()>,
            )
            .await
    }
    pub async fn get_owned_asset_by_universe_index(
        &self,
        index: u32,
    ) -> Result<live::AssetOwnership, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &[
                    "assets".to_string(),
                    "ownerships".to_string(),
                    index.to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_possessed_assets_by_filter(
        &self,
        query: &GetPossessedAssetsByFilterQuery,
    ) -> Result<live::AssetPossessions, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &["assets".to_string(), "possessions".to_string()],
                Some(query),
                None::<&()>,
            )
            .await
    }
    pub async fn get_possessed_asset_by_universe_index(
        &self,
        index: u32,
    ) -> Result<live::AssetPossession, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &[
                    "assets".to_string(),
                    "possessions".to_string(),
                    index.to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_issued_assets(
        &self,
        identity: String,
    ) -> Result<live::IssuedAssetsResponse, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &[
                    "assets".to_string(),
                    identity.to_string(),
                    "issued".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_owned_assets(
        &self,
        identity: String,
    ) -> Result<live::OwnedAssetsResponse, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &[
                    "assets".to_string(),
                    identity.to_string(),
                    "owned".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_possessed_assets(
        &self,
        identity: String,
    ) -> Result<live::PossessedAssetsResponse, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &[
                    "assets".to_string(),
                    identity.to_string(),
                    "possessed".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_balance(&self, id: String) -> Result<live::GetBalanceResponse, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &["balances".to_string(), id.to_string()],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_block_height(&self) -> Result<live::GetBlockHeightResponse, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &["block-height".to_string()],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn broadcast_transaction(
        &self,
        body: &live::BroadcastTransactionRequest,
    ) -> Result<live::BroadcastTransactionResponse, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::POST,
                &["broadcast-transaction".to_string()],
                None::<&()>,
                Some(body),
            )
            .await
    }
    pub async fn get_active_ipos(&self) -> Result<live::GetActiveIposResponse, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &["ipos".to_string(), "active".to_string()],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_contract_ipo_bids(
        &self,
        contract_index: u32,
    ) -> Result<live::GetContractIpoBidsResponse, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &[
                    "ipos".to_string(),
                    contract_index.to_string(),
                    "bids".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn query_smart_contract(
        &self,
        body: &live::QuerySmartContractRequest,
    ) -> Result<live::QuerySmartContractResponse, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::POST,
                &["querySmartContract".to_string()],
                None::<&()>,
                Some(body),
            )
            .await
    }
    pub async fn get_tick_info(&self) -> Result<live::GetTickInfoResponse, ClientError> {
        self.0
            .request(
                &self.0.config.live_url,
                Method::GET,
                &["tick-info".to_string()],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
}

impl QueryApi<'_> {
    pub async fn get_computors_lists_for_epoch(
        &self,
        body: &query::GetComputorListsForEpochRequest,
    ) -> Result<query::GetComputorListsForEpochResponse, ClientError> {
        self.0
            .request(
                &self.0.config.query_url,
                Method::POST,
                &["getComputorListsForEpoch".to_string()],
                None::<&()>,
                Some(body),
            )
            .await
    }
    pub async fn get_event_logs(
        &self,
        body: &query::GetEventLogsRequest,
    ) -> Result<query::GetEventLogsResponse, ClientError> {
        self.0
            .request(
                &self.0.config.query_url,
                Method::POST,
                &["getEventLogs".to_string()],
                None::<&()>,
                Some(body),
            )
            .await
    }
    pub async fn get_last_processed_tick(
        &self,
    ) -> Result<query::GetLastProcessedTickResponse, ClientError> {
        self.0
            .request(
                &self.0.config.query_url,
                Method::GET,
                &["getLastProcessedTick".to_string()],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_processed_tick_intervals(
        &self,
    ) -> Result<query::GetProcessedTickIntervalsResponse, ClientError> {
        self.0
            .request(
                &self.0.config.query_url,
                Method::GET,
                &["getProcessedTickIntervals".to_string()],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_tick_data(
        &self,
        body: &query::GetTickDataRequest,
    ) -> Result<query::GetTickDataResponse, ClientError> {
        self.0
            .request(
                &self.0.config.query_url,
                Method::POST,
                &["getTickData".to_string()],
                None::<&()>,
                Some(body),
            )
            .await
    }
    pub async fn get_transaction_by_hash(
        &self,
        body: &query::GetTransactionByHashRequest,
    ) -> Result<query::GetTransactionByHashResponse, ClientError> {
        self.0
            .request(
                &self.0.config.query_url,
                Method::POST,
                &["getTransactionByHash".to_string()],
                None::<&()>,
                Some(body),
            )
            .await
    }
    pub async fn get_transactions_for_identity(
        &self,
        body: &query::GetTransactionsForIdentityRequest,
    ) -> Result<query::GetTransactionsForIdentityResponse, ClientError> {
        self.0
            .request(
                &self.0.config.query_url,
                Method::POST,
                &["getTransactionsForIdentity".to_string()],
                None::<&()>,
                Some(body),
            )
            .await
    }
    pub async fn get_transactions_for_tick(
        &self,
        body: &query::GetTransactionsForTickRequest,
    ) -> Result<query::GetTransactionsForTickResponse, ClientError> {
        self.0
            .request(
                &self.0.config.query_url,
                Method::POST,
                &["getTransactionsForTick".to_string()],
                None::<&()>,
                Some(body),
            )
            .await
    }
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GetTransferTransactionsPerTickQuery {
    #[serde(rename = "startTick", default, skip_serializing_if = "Option::is_none")]
    pub start_tick: Option<i64>,
    #[serde(rename = "endTick", default, skip_serializing_if = "Option::is_none")]
    pub end_tick: Option<i64>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GetEmptyTickListV2Query {
    #[serde(rename = "page", default, skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    #[serde(rename = "pageSize", default, skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GetEpochTickListV2Query {
    #[serde(rename = "page", default, skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    #[serde(rename = "pageSize", default, skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    #[serde(rename = "desc", default, skip_serializing_if = "Option::is_none")]
    pub desc: Option<bool>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GetIdentityTransfersInTickRangeV2Query {
    #[serde(rename = "startTick", default, skip_serializing_if = "Option::is_none")]
    pub start_tick: Option<i64>,
    #[serde(rename = "endTick", default, skip_serializing_if = "Option::is_none")]
    pub end_tick: Option<i64>,
    #[serde(rename = "scOnly", default, skip_serializing_if = "Option::is_none")]
    pub sc_only: Option<bool>,
    #[serde(rename = "desc", default, skip_serializing_if = "Option::is_none")]
    pub desc: Option<bool>,
    #[serde(rename = "page", default, skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(rename = "pageSize", default, skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i64>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GetTickTransactionsV2Query {
    #[serde(rename = "transfers", default, skip_serializing_if = "Option::is_none")]
    pub transfers: Option<bool>,
    #[serde(rename = "approved", default, skip_serializing_if = "Option::is_none")]
    pub approved: Option<bool>,
}

impl ArchiveApi<'_> {
    pub async fn get_computors(
        &self,
        epoch: i64,
    ) -> Result<archive::pbGetComputorsResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v1".to_string(),
                    "epochs".to_string(),
                    epoch.to_string(),
                    "computors".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_health_check(&self) -> Result<archive::pbGetHealthCheckResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &["v1".to_string(), "healthcheck".to_string()],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_transfer_transactions_per_tick(
        &self,
        identity: String,
        query: &GetTransferTransactionsPerTickQuery,
    ) -> Result<archive::pbGetTransferTransactionsPerTickResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v1".to_string(),
                    "identities".to_string(),
                    identity.to_string(),
                    "transfer-transactions".to_string(),
                ],
                Some(query),
                None::<&()>,
            )
            .await
    }
    pub async fn get_latest_tick(&self) -> Result<archive::pbGetLatestTickResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &["v1".to_string(), "latestTick".to_string()],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_status(&self) -> Result<archive::pbGetStatusResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &["v1".to_string(), "status".to_string()],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_tick_approved_transactions(
        &self,
        tick_number: i64,
    ) -> Result<archive::pbGetTickApprovedTransactionsResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v1".to_string(),
                    "ticks".to_string(),
                    tick_number.to_string(),
                    "approved-transactions".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_chain_hash(
        &self,
        tick_number: i64,
    ) -> Result<archive::pbGetChainHashResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v1".to_string(),
                    "ticks".to_string(),
                    tick_number.to_string(),
                    "chain-hash".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_quorum_tick_data(
        &self,
        tick_number: i64,
    ) -> Result<archive::pbGetQuorumTickDataResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v1".to_string(),
                    "ticks".to_string(),
                    tick_number.to_string(),
                    "quorum-tick-data".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_store_hash(
        &self,
        tick_number: i64,
    ) -> Result<archive::pbGetChainHashResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v1".to_string(),
                    "ticks".to_string(),
                    tick_number.to_string(),
                    "store-hash".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_tick_data(
        &self,
        tick_number: i64,
    ) -> Result<archive::pbGetTickDataResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v1".to_string(),
                    "ticks".to_string(),
                    tick_number.to_string(),
                    "tick-data".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_tick_transactions(
        &self,
        tick_number: i64,
    ) -> Result<archive::pbGetTickTransactionsResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v1".to_string(),
                    "ticks".to_string(),
                    tick_number.to_string(),
                    "transactions".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_tick_transfer_transactions(
        &self,
        tick_number: i64,
    ) -> Result<archive::pbGetTickTransactionsResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v1".to_string(),
                    "ticks".to_string(),
                    tick_number.to_string(),
                    "transfer-transactions".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_transaction(
        &self,
        tx_id: String,
    ) -> Result<archive::pbGetTransactionResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v1".to_string(),
                    "transactions".to_string(),
                    tx_id.to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_transaction_status(
        &self,
        tx_id: String,
    ) -> Result<archive::pbGetTransactionStatusResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &["v1".to_string(), "tx-status".to_string(), tx_id.to_string()],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_empty_tick_list_v2(
        &self,
        epoch: i64,
        query: &GetEmptyTickListV2Query,
    ) -> Result<archive::pbGetEmptyTickListResponseV2, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v2".to_string(),
                    "epochs".to_string(),
                    epoch.to_string(),
                    "empty-ticks".to_string(),
                ],
                Some(query),
                None::<&()>,
            )
            .await
    }
    pub async fn get_epoch_tick_list_v2(
        &self,
        epoch: i64,
        query: &GetEpochTickListV2Query,
    ) -> Result<archive::pbGetEpochTickListResponseV2, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v2".to_string(),
                    "epochs".to_string(),
                    epoch.to_string(),
                    "ticks".to_string(),
                ],
                Some(query),
                None::<&()>,
            )
            .await
    }
    pub async fn get_identity_transfers_in_tick_range_v2(
        &self,
        identity: String,
        query: &GetIdentityTransfersInTickRangeV2Query,
    ) -> Result<archive::pbGetIdentityTransfersInTickRangeResponseV2, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v2".to_string(),
                    "identities".to_string(),
                    identity.to_string(),
                    "transfers".to_string(),
                ],
                Some(query),
                None::<&()>,
            )
            .await
    }
    pub async fn get_tick_chain_hash_v2(
        &self,
        tick_number: i64,
    ) -> Result<archive::pbGetChainHashResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v2".to_string(),
                    "ticks".to_string(),
                    tick_number.to_string(),
                    "hash".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_tick_quorum_data_v2(
        &self,
        tick_number: i64,
    ) -> Result<archive::pbGetQuorumTickDataResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v2".to_string(),
                    "ticks".to_string(),
                    tick_number.to_string(),
                    "quorum-data".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_tick_store_hash_v2(
        &self,
        tick_number: i64,
    ) -> Result<archive::pbGetChainHashResponse, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v2".to_string(),
                    "ticks".to_string(),
                    tick_number.to_string(),
                    "store-hash".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_tick_transactions_v2(
        &self,
        tick_number: i64,
        query: &GetTickTransactionsV2Query,
    ) -> Result<archive::pbGetTickTransactionsResponseV2, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v2".to_string(),
                    "ticks".to_string(),
                    tick_number.to_string(),
                    "transactions".to_string(),
                ],
                Some(query),
                None::<&()>,
            )
            .await
    }
    pub async fn get_transaction_v2(
        &self,
        tx_id: String,
    ) -> Result<archive::pbGetTransactionResponseV2, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v2".to_string(),
                    "transactions".to_string(),
                    tx_id.to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_send_many_transaction_v2(
        &self,
        tx_id: String,
    ) -> Result<archive::pbGetSendManyTransactionResponseV2, ClientError> {
        self.0
            .request(
                &self.0.config.archive_url,
                Method::GET,
                &[
                    "v2".to_string(),
                    "transactions".to_string(),
                    tx_id.to_string(),
                    "sendmany".to_string(),
                ],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GetAssetOwnersQuery {
    #[serde(rename = "page", default, skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(rename = "pageSize", default, skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i64>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GetRichListSliceQuery {
    #[serde(rename = "page", default, skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    #[serde(rename = "pageSize", default, skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
}

impl StatsApi<'_> {
    pub async fn get_asset_owners(
        &self,
        issuer_identity: String,
        asset_name: String,
        query: &GetAssetOwnersQuery,
    ) -> Result<stats::pbGetAssetOwnershipResponse, ClientError> {
        self.0
            .request(
                &self.0.config.stats_url,
                Method::GET,
                &[
                    "v1".to_string(),
                    "issuers".to_string(),
                    issuer_identity.to_string(),
                    "assets".to_string(),
                    asset_name.to_string(),
                    "owners".to_string(),
                ],
                Some(query),
                None::<&()>,
            )
            .await
    }
    pub async fn get_latest_data(&self) -> Result<stats::pbGetLatestDataResponse, ClientError> {
        self.0
            .request(
                &self.0.config.stats_url,
                Method::GET,
                &["v1".to_string(), "latest-stats".to_string()],
                None::<&()>,
                None::<&()>,
            )
            .await
    }
    pub async fn get_rich_list_slice(
        &self,
        query: &GetRichListSliceQuery,
    ) -> Result<stats::pbGetRichListSliceResponse, ClientError> {
        self.0
            .request(
                &self.0.config.stats_url,
                Method::GET,
                &["v1".to_string(), "rich-list".to_string()],
                Some(query),
                None::<&()>,
            )
            .await
    }
}
